name: Check UpdateID's

on:
  workflow_dispatch:

jobs:
  Archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and install Python
        uses: actions/checkout@v3.5.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          echo "Installing dependencies"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: false  # Set this to false to stop the workflow if the step fails

      - name: Run Archive script
        id: check_archive_status
        working-directory: updateids
        run: |
          if python ../update.py; then
            echo "Archive script succeeded!"
            echo "success" > ../status.txt
          else
            echo "Archive script failed!"
            echo "failure" > ../status.txt
            exit 1
          fi
        continue-on-error: false  # Set this to false to stop the workflow if the step fails

      - name: Commit and push changes - updated list
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./updateids
          git commit -m "Updated updateid list"
          git push origin ${{ github.ref }}
        continue-on-error: true
